services:
  app:
    image: hseeberger/scala-sbt:8u265_1.4.5_2.13.4
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db
      - localstack
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.ivy2:/root/.ivy2
      - coursier-catch:/root/.cache/coursier
  db:
    image: library/mysql:8.0
    environment:
      - MYSQL_DATABASE=db_orders
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_USER=mysql
    ports:
      - 3306:3306
    volumes:
      - mysqldata:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs,sns
      - DEBUG=${DEBUG- }
      - DEFAULT_REGION=ap-east-1
      - HOSTNAME=localstack
      # - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./ops/local:/docker-entrypoint-initaws.d

volumes:
  mysqldata: {}
  coursier-catch: {}
